version: 2
jobs:
  build_test_deploy:
    machine: true
    steps:
      - checkout

      - run:
          name: Build docker container
          command: docker build -t "racemap/tz-service:${CIRCLE_BUILD_NUM}" .

      - run:
          name: Run local tests
          command: |
            docker run \
              --rm \
              -d \
              -p8080:8080 \
              --name tz-service \
              "racemap/tz-service:${CIRCLE_BUILD_NUM}"
            sleep 10
            RESULT=$(curl "http://localhost:8080/api?lng=32.408843&lat=104.505033")
            [ "$RESULT" = "{\"name\":\"Asia/Shanghai\",\"id\":\"CST\",\"offset\":28800}" ]
            docker stop tz-service

      - run:
          name: Push Docker images
          command: |
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker tag \
              "racemap/tz-service:${CIRCLE_BUILD_NUM}" \
              "racemap/tz-service:${CIRCLE_BRANCH}"
            docker push "racemap/tz-service:${CIRCLE_BUILD_NUM}"
            docker push "racemap/tz-service:${CIRCLE_BRANCH}"
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag \
                "racemap/tz-service:${CIRCLE_BUILD_NUM}" \
                "racemap/tz-service:latest"
              docker push "racemap/tz-service:latest"
            fi
            docker logout

workflows:
  version: 2
  default:
    jobs:
      - build_test_deploy
